### ISSUE TITLE
Linear modifier for x() fails with exception when used with stack

### ISSUE THREAD

**Issue by danrope** [Brunel-Visualization/Brunel#204]
The following Brunel:
`x(age:linear) y(price) stack color(category) mean(price)`

throws a Java exception:

`java.lang.IllegalArgumentException: Could not find field: Age:linear
	at org.brunel.data.modify.Stack.getField(Stack.java:78)
	at org.brunel.data.modify.Stack.getFields(Stack.java:88)
	at org.brunel.data.modify.Stack.transform(Stack.java:59)
	at org.brunel.data.Dataset.stack(Dataset.java:292)`

Seems to only happen on `x()`.

**Comment by danrope** [comment]
Confirmed fix from Graham.
