### ISSUE TITLE
Illegal Argument Exception

### ISSUE THREAD

**Issue by ytang327** [Brunel-Visualization/Brunel#225]
Trying to run some brunel visualizations in a jupyter notebook with an apache toree kernel on an x86 system. Apache toree connects to a spark 2.0.2 cluster running on a z/os system and uses kernel gateway to communicate with the jupyter kernel. 

When I try to run any brunel visualizations I run into the following stacktrace:

java.lang.IllegalArgumentException: Could not read data from: dataRate
	at org.brunel.build.util.ContentReader.readContentFromUrl(ContentReader.java:42)
	at org.brunel.build.util.DataCache.get(DataCache.java:117)
	at org.brunel.build.util.DataCache.get(DataCache.java:68)
	at org.brunel.model.VisElement.getDataset(VisElement.java:158)
	at org.brunel.model.VisElement.getDataSets(VisElement.java:306)
	at org.brunel.build.VisualizationBuilder.build(VisualizationBuilder.java:92)
	at org.brunel.util.D3Integration.makeD3(D3Integration.java:166)
	at org.brunel.scala.Brunel$.create(Brunel.scala:49)
	at org.brunel.toree.Brunel.execute(Brunel.scala:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at org.apache.toree.plugins.PluginMethod$$anonfun$invoke$2.apply(PluginMethod.scala:116)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.toree.plugins.PluginMethod.invoke(PluginMethod.scala:84)
	at org.apache.toree.plugins.PluginManager$$anonfun$8.apply(PluginManager.scala:334)
	at org.apache.toree.plugins.PluginManager$$anonfun$8.apply(PluginManager.scala:333)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:285)
	at org.apache.toree.plugins.PluginManager.invokePluginMethods(PluginManager.scala:333)
	at org.apache.toree.plugins.PluginManager.fireEvent(PluginManager.scala:300)
	at org.apache.toree.plugins.PluginManager.fireEvent(PluginManager.scala:283)
	at org.apache.toree.plugins.PluginManager.fireEventFirstResult(PluginManager.scala:250)
	at org.apache.toree.magic.MagicManager.applyDynamic(MagicManager.scala:82)
	at $line38.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:21)
	at $line38.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:27)
	at $line38.$read$$iw$$iw$$iw$$iw.<init>(<console>:29)
	at $line38.$read$$iw$$iw$$iw.<init>(<console>:31)
	at $line38.$read$$iw$$iw.<init>(<console>:33)
	at $line38.$read$$iw.<init>(<console>:35)
	at $line38.$read.<init>(<console>:37)
	at $line38.$read$.<init>(<console>:41)
	at $line38.$read$.<clinit>(<console>)
	at $line38.$eval$.$print$lzycompute(<console>:7)
	at $line38.$eval$.$print(<console>:6)
	at $line38.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:95)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
	at java.lang.reflect.Method.invoke(Method.java:508)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:637)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:569)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:565)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreterSpecific$$anonfun$interpretAddTask$1$$anonfun$apply$3.apply(ScalaInterpreterSpecific.scala:344)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreterSpecific$$anonfun$interpretAddTask$1$$anonfun$apply$3.apply(ScalaInterpreterSpecific.scala:339)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withErr(Console.scala:80)
	at org.apache.toree.global.StreamState$$anonfun$1$$anonfun$apply$1.apply(StreamState.scala:73)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withOut(Console.scala:53)
	at org.apache.toree.global.StreamState$$anonfun$1.apply(StreamState.scala:72)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withIn(Console.scala:124)
	at org.apache.toree.global.StreamState$.withStreams(StreamState.scala:71)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreterSpecific$$anonfun$interpretAddTask$1.apply(ScalaInterpreterSpecific.scala:338)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreterSpecific$$anonfun$interpretAddTask$1.apply(ScalaInterpreterSpecific.scala:338)
	at org.apache.toree.utils.TaskManager$$anonfun$add$2$$anon$1.run(TaskManager.scala:140)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1153)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.lang.Thread.run(Thread.java:785)
Out[25]:
Left(Map(text/plain -> Magic brunel failed to execute with error:
Could not execute Brunel: data('dataRate') x(MONTH) y(RATE) bar tooltip(#all) sort(DAY:ascending) tooltip(#all) axes(x:'Time', y:'Rate':grid)))

The cell that is ran:
%%brunel data('dataRate') x(MONTH) y(RATE) bar tooltip(#all) sort(DAY:ascending) tooltip(#all) axes(x:'Time', y:'Rate':grid) 
:: width=800, height=500

And dataRate is loaded in a previous cell that is executed before this one, so I know dataRate actually exists...

This is the cell that loads the dataRate: (removed actual hostname, username, etc..)

val dataRate = spark.read.format("jdbc").
                        options(Map("driver" -> "com.ibm.db2.jcc.DB2Driver",
                         "url" -> "jdbc:db2://hostname:port/....", 
                         "user" -> "user-name","password" -> "password", 
                         "dbtable" -> "DB.DATA_RATE")).load()

dataRate ends up being populated with what I need.

Any thoughts why I'm getting an illegal argument exception?

**Comment by ivandov** [comment]
What did you do to resolve this? Hit a similar issue with Jupyter on Linux s390x and Spark 2.0.2
