### ISSUE TITLE
Mystery:  Brunel Toree error

### ISSUE THREAD

**Issue by ckevinhill** [Brunel-Visualization/Brunel#243]
I can't seem to make any progress figuring this one out.  It looks like some sort of incompatibility between toree and brunel so I'm guessing version issue.

I think I'm using toree-0.2.0.dev1, Spark 2.0, Scala 2.11.8 and spark-kernel-brunel-all-2.4.jar.  Thanks in advance for any pointers... full stacktrace below. 

17/07/18 17:46:35 WARN magic.MagicManager: Magic brunel failed to execute with error:                                                     
org.apache.toree.magic.package$.CellMagicOutput()Lscala/collection/immutable/Map$;                                                        
java.lang.NoSuchMethodError: org.apache.toree.magic.package$.CellMagicOutput()Lscala/collection/immutable/Map$;                           
        at org.brunel.toree.Brunel.execute(Brunel.scala:134)                                                                              
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                    
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                  
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                          
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                               
        at org.apache.toree.plugins.PluginMethod$$anonfun$invoke$2.apply(PluginMethod.scala:116)                                          
        at scala.util.Try$.apply(Try.scala:192)                                                                                           
        at org.apache.toree.plugins.PluginMethod.invoke(PluginMethod.scala:84)                                                            
        at org.apache.toree.plugins.PluginManager$$anonfun$8.apply(PluginManager.scala:334)                                               
        at org.apache.toree.plugins.PluginManager$$anonfun$8.apply(PluginManager.scala:333)                                               
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)                                               
        at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)                                               
        at scala.collection.immutable.List.foreach(List.scala:381)                                                                        
        at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)                                                          
        at scala.collection.immutable.List.map(List.scala:285)                                                                            
        at org.apache.toree.plugins.PluginManager.invokePluginMethods(PluginManager.scala:333)                                            
        at org.apache.toree.plugins.PluginManager.fireEvent(PluginManager.scala:300)                                                      
        at org.apache.toree.plugins.PluginManager.fireEvent(PluginManager.scala:283)                                                      
        at org.apache.toree.plugins.PluginManager.fireEventFirstResult(PluginManager.scala:250)                                           
        at org.apache.toree.magic.MagicManager.applyDynamic(MagicManager.scala:82)                                                        
        at $line51.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:26)                                                                     
        at $line51.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:31)                                                                         
        at $line51.$read$$iw$$iw$$iw$$iw.<init>(<console>:33)                                                                             
        at $line51.$read$$iw$$iw$$iw.<init>(<console>:35)                                                                                 
        at $line51.$read$$iw$$iw.<init>(<console>:37)                                                                                     
        at $line51.$read$$iw.<init>(<console>:39)                                                                                         
        at $line51.$read.<init>(<console>:41)                                                                                             
        at $line51.$read$.<init>(<console>:45)                                                                                            
        at $line51.$read$.<clinit>(<console>)                                                                                             
        at $line51.$eval$.$print$lzycompute(<console>:7)                                                                                  
        at $line51.$eval$.$print(<console>:6)                                                                                             
        at $line51.$eval.$print(<console>)                                                                                                
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)                                                                    
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)                                                  
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)                                          
        at java.lang.reflect.Method.invoke(Method.java:498)                                                                               
        at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:786)                                                          
        at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1047)                                                         
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:638)                               
        at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:637)                               
        at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)                                        
        at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)

**Comment by ckevinhill** [comment]
Comparing versions of environments to try and triangulate who is causing the issue.  Right now best bet seems Cloudera 2.0.0 spark libraries....?

          | Local VM | Vendor Server | AWS Cluster
Spark | 2.2.0 | 2.0.2 | 2.0.0.cloudera 2
Scala | 2.11.8 | 2.11.8 | 2.11.8
Brunel | 2.4 | 2.4 | 2.4
Jupyter | 4.2.0 | 4.3.0 | 4.3.0
Toree | 0.2.0-dev1 | 0.2.0-dev1 | 0.2.0-dev1
Status | Works | Works | Doesn’t Work

**Comment by ytang327** [comment]
Also running into this problem. Any advancement on this?

**Comment by xuexuemiao** [comment]
Also running into the same problem. 

`spark 2.4.0`

`%AddJar -magic https://brunelvis.org/jar/spark-kernel-brunel-all-2.6.jar`

```
jovyan@spark-jupyterhub:~$ jupyter notebook --version
5.7.0
```

```
jovyan@spark-jupyterhub:~$ jupyter toree -v
Functions for managing the Apache Toree kernel. This package was built with the
following versions of Apache Toree and Spark:

        Apache Toree Version: 0.3.0
        Apache Toree Build Commit: 3ff5df33cc45

```

```
2018-11-19 19:02:37 WARN  MagicManager:111 - Magic brunel failed to execute with error:
org.apache.toree.magic.package$.CellMagicOutput()Lscala/collection/immutable/Map$;
java.lang.NoSuchMethodError: org.apache.toree.magic.package$.CellMagicOutput()Lscala/collection/immutable/Map$;
	at org.brunel.toree.Brunel.execute(Brunel.scala:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.toree.plugins.PluginMethod$$anonfun$invoke$2.apply(PluginMethod.scala:116)
	at scala.util.Try$.apply(Try.scala:192)
	at org.apache.toree.plugins.PluginMethod.invoke(PluginMethod.scala:84)
	at org.apache.toree.plugins.PluginManager$$anonfun$8.apply(PluginManager.scala:334)
	at org.apache.toree.plugins.PluginManager$$anonfun$8.apply(PluginManager.scala:333)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at org.apache.toree.plugins.PluginManager.invokePluginMethods(PluginManager.scala:333)
	at org.apache.toree.plugins.PluginManager.fireEvent(PluginManager.scala:300)
	at org.apache.toree.plugins.PluginManager.fireEvent(PluginManager.scala:283)
	at org.apache.toree.plugins.PluginManager.fireEventFirstResult(PluginManager.scala:250)
	at org.apache.toree.magic.MagicManager.applyDynamic(MagicManager.scala:82)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:74)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:79)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:81)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:83)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:85)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:87)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:89)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:91)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:93)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:95)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:97)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:99)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:101)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:103)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:105)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:107)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:109)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:111)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(<console>:113)
	at $line88.$read$$iw$$iw$$iw$$iw$$iw.<init>(<console>:115)
	at $line88.$read$$iw$$iw$$iw$$iw.<init>(<console>:117)
	at $line88.$read$$iw$$iw$$iw.<init>(<console>:119)
	at $line88.$read$$iw$$iw.<init>(<console>:121)
	at $line88.$read$$iw.<init>(<console>:123)
	at $line88.$read.<init>(<console>:125)
	at $line88.$read$.<init>(<console>:129)
	at $line88.$read$.<clinit>(<console>)
	at $line88.$eval$.$print$lzycompute(<console>:7)
	at $line88.$eval$.$print(<console>:6)
	at $line88.$eval.$print(<console>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:793)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1054)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:645)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest$$anonfun$loadAndRunReq$1.apply(IMain.scala:644)
	at scala.reflect.internal.util.ScalaClassLoader$class.asContext(ScalaClassLoader.scala:31)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:19)
	at scala.tools.nsc.interpreter.IMain$WrappedRequest.loadAndRunReq(IMain.scala:644)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:576)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:572)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreterSpecific$$anonfun$interpretAddTask$1$$anonfun$apply$3.apply(ScalaInterpreterSpecific.scala:385)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreterSpecific$$anonfun$interpretAddTask$1$$anonfun$apply$3.apply(ScalaInterpreterSpecific.scala:380)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withErr(Console.scala:80)
	at org.apache.toree.global.StreamState$$anonfun$1$$anonfun$apply$1.apply(StreamState.scala:73)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withOut(Console.scala:53)
	at org.apache.toree.global.StreamState$$anonfun$1.apply(StreamState.scala:72)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:58)
	at scala.Console$.withIn(Console.scala:124)
	at org.apache.toree.global.StreamState$.withStreams(StreamState.scala:71)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreterSpecific$$anonfun$interpretAddTask$1.apply(ScalaInterpreterSpecific.scala:379)
	at org.apache.toree.kernel.interpreter.scala.ScalaInterpreterSpecific$$anonfun$interpretAddTask$1.apply(ScalaInterpreterSpecific.scala:379)
	at org.apache.toree.utils.TaskManager$$anonfun$add$2$$anon$2.run(TaskManager.scala:134)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2018-11-19 19:02:37 WARN  KernelOutputStream:98 - Suppressing empty output: ''
```

**Comment by xuexuemiao** [comment]
I tried adding brunel jar to SPARK_OPTS, it looked like partially work. The browser(both chrome 70.0.3538.102 and safari 12.0.1 (14606.2.104.1.1)) complained about this problem.


![image](https://user-images.githubusercontent.com/7149846/48763574-89025780-ece8-11e8-95ad-55345ef30b94.png)


![image](https://user-images.githubusercontent.com/7149846/48763696-c535b800-ece8-11e8-9d3b-ba3070251bbc.png)


![image](https://user-images.githubusercontent.com/7149846/48764524-d8498780-ecea-11e8-8576-42140083199a.png)

**Comment by xuexuemiao** [comment]
finally, we use a script injector which is a chrome extension to supply the scripts we need.

![image](https://user-images.githubusercontent.com/7149846/49005689-4a661480-f1a2-11e8-8d3d-678fbc752781.png)

![image](https://user-images.githubusercontent.com/7149846/49005706-5651d680-f1a2-11e8-9be7-e4a23bf61879.png)
