### ISSUE TITLE
pip install brunel error

### ISSUE THREAD

**Issue by opokualbert** [Brunel-Visualization/Brunel#298]
Hello - 
I tried to pip install brunel but I get this error:
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-oxnvqc7e/brunel/

Please take a look into this issue and help out.
Thanks!
Albert.

**Comment by danfike** [comment]
I'm having trouble installing `brunel` with `pip` too. It just started today, after upgrading to `pip 10.0.0`.

```
$ pip install brunel
Collecting brunel
  Downloading https://files.pythonhosted.org/packages/5d/94/20ad0cb14c6ee0c873aa377b4edffc72b93c98221771e898eafb128433f3/brunel-2.3.tar.gz (2.1MB)
    .....
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/7l/psm5gvkj4c3bl4h83_kzz88r0000gn/T/pip-install-sybwjd/brunel/setup.py", line 30, in <module>
        pip.main(['install', 'jupyter-pip']); cmdclass = importlib.import_module('jupyterpip').cmdclass
    AttributeError: 'module' object has no attribute 'main'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/7l/psm5gvkj4c3bl4h83_kzz88r0000gn/T/pip-install-sybwjd/brunel/
```

https://github.com/Brunel-Visualization/Brunel/blob/937a26cae654607dfbb0b569ec19ded521a7649e/python/setup.py#L30

It looks like the `10.0.0` version of `pip` has removed the `pip.main()` function and buried it at `pip._internal.main`

**Comment by danfike** [comment]
@opalbert If your problem is the same as mine, you can temporarily work around the issue by explicitly installing `jupyterpip` manually before installing `brunel`

```
pip install jupyter-pip
```

**Comment by opalbert** [comment]
@danfike Thank you for your suggestion, the installation almost worked except that I get this new error which seems to me I need to install Java/JDK:
"RuntimeError: No Java/JDK could be found. I looked in the following directories:
    
    /usr/lib/jvm/jre-1.7.0
    /usr/lib/jvm/jre-1.6.0
    /usr/lib/jvm/jre-openjdk
    /usr/lib/jvm/java-1.6.0-openjdk-1.6.0.41.x86_64
    /usr/lib/jvm/jre
    /usr/lib/jvm/jre-1.6.0-openjdk.x86_64
    /usr/lib/jvm/jre-1.7.0-openjdk.x86_64
    /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.171.x86_64
    /usr/lib/jvm/java-1.7.0-openjdk-1.7.0.161.x86_64
    
    Please check that you have it installed.
    
    If you have and the destination is not in the above list, please find out where your java's home is, set your JAVA_HOME environment variable to that path and retry the installation.
    If this still fails please open a ticket or create a pull request with a fix on github:
    https://github.com/tcalmant/jpype/
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-tydkch7j/JPype1-py3/"

**Comment by opokualbert** [comment]
After installing pip install jupyter-pip on a new machine, pip install brunel works.
Thanks all.
This may be closed.
