### ISSUE TITLE
Nullpointer exception when providing scale transform for y axis with multiple data sets

### ISSUE THREAD

**Issue by AlecZorab** [Brunel-Visualization/Brunel#89]
In the gallery, editing the "series lines" example to: `data('sample:Unemployment.csv') x(#row) y(Women:linear, Men) color(#series) line`. Generates a Null error. Similarly, a NPE is thrown using jupyter and toree, with the following stack trace:

```
java.lang.NullPointerException
	at org.brunel.data.modify.ConvertSeries.transform(ConvertSeries.java:79)
	at org.brunel.data.Dataset.series(Dataset.java:234)
	at org.brunel.build.data.DataBuilder.build(DataBuilder.java:92)
	at org.brunel.build.AbstractBuilder.buildSingleChart(AbstractBuilder.java:202)
	at org.brunel.build.AbstractBuilder.buildTiledCharts(AbstractBuilder.java:223)
	at org.brunel.build.AbstractBuilder.build(AbstractBuilder.java:103)
	at org.brunel.util.D3Integration.makeD3(D3Integration.java:166)
	at org.brunel.scala.Brunel$.create(Brunel.scala:49)
	at org.apache.toree.magic.builtin.Brunel.execute(Brunel.scala:70)
	at sun.reflect.GeneratedMethodAccessor59.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.apache.toree.utils.DynamicReflectionSupport.invokeMethod(DynamicReflectionSupport.scala:107)
	at org.apache.toree.utils.DynamicReflectionSupport.applyDynamic(DynamicReflectionSupport.scala:79)
	at org.apache.toree.magic.MagicExecutor.executeMagic(MagicExecutor.scala:49)
	at org.apache.toree.magic.MagicExecutor.applyDynamic(MagicExecutor.scala:35)
	at $line119.$read$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC$$iwC.<init>(<console>:44)
```

**Comment by danrope** [comment]
Graham fixed on develop.  The first specified scale will win since mixed scales for `#series` are not allowed.
